version: "3.8"

services:
  django_backend:
    build: ./backend
    command: >
      sh -c "sleep ${DJANGO_DELAY} && python manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"
    env_file:
      - .env
    volumes: 
      - ./backend:/app
    ports: 
      - "8000:8000"
    depends_on:
      - postgres
      - redis
      - kafka
