version: "3.8"

services:
  fastapi_service:
    build: ./fastapi_service
    command: >
      sh -c "sleep ${FASTAPI_DELAY} && uvicorn main:app --host 0.0.0.0 --port 8001"
    env_file:
      - .env
    volumes: 
      - ./fastapi_service:/app
    ports: 
      - "8001:8001"
    depends_on:
      - kafka
      - redis
      - postgres